#!/bin/bash
ROOTDIR=/opt/wifioss/errdb

RRDTOOL_POOL=9

for ((  i = 0 ; i <= $RRDTOOL_POOL; i++  ))
do
  JOURNAL=$ROOTDIR/var/data/rrdcached${i}
  PID=$ROOTDIR/var/pids/rrdcached${i}.pid
  if [ -f $PID ]
  then
    kill -9 `cat $PID`
  fi
  SOCK=unix:$ROOTDIR/var/sock/rrdcached${i}.sock
  mkdir -p $JOURNAL
  rrdcached -w 1200 -z 600 -t 8 -l $SOCK -p $PID -j $JOURNAL
  echo "start rrdcached ${i}...done"
done

LOG_LEVEL=4

LOG_PATH=$ROOTDIR/var/log/errdb.log

erl -noinput -detached -smp auto +K true -name errdb@opengoss.com -pa ./ebin -config etc/errdb/errdb -boot start_sasl -s reloader -s errdb_app -log_level $LOG_LEVEL -log_path $LOG_PATH -rrdtool_pool $RRDTOOL_POOL -rrdcached_sock unix:$ROOTDIR/var/sock

# 
